import type { ClaimCase, DashboardStats } from '@/types'

export const MOCK_CASES: ClaimCase[] = [
  {
    id: 'FRA-2024-001',
    applicantName: 'Ramesh Munda',
    village: 'Chakradharpur',
    district: 'West Singhbhum',
    state: 'Jharkhand',
    claimType: 'Individual',
    status: 'Under Review',
    submittedDate: '2024-03-15',
    lastUpdated: '2024-06-10',
    area: 2.5,
    documents: ['Land Map', 'Gram Sabha Resolution', 'Identity Proof'],
    officerAssigned: 'DFO Sharma',
    priority: 'High',
    notes: 'Third generation forest dweller. Strong documentary evidence.',
  },
  {
    id: 'FRA-2024-002',
    applicantName: 'Saraswati Oraon',
    village: 'Lohardaga',
    district: 'Lohardaga',
    state: 'Jharkhand',
    claimType: 'Community',
    status: 'Approved',
    submittedDate: '2023-11-20',
    lastUpdated: '2024-05-01',
    area: 18.3,
    documents: ['Community Map', 'Gram Sabha Minutes', 'Old Records', 'Photos'],
    officerAssigned: 'DFO Patel',
    priority: 'Medium',
  },
  {
    id: 'FRA-2024-003',
    applicantName: 'Bhushan Gond',
    village: 'Mandla',
    district: 'Mandla',
    state: 'Madhya Pradesh',
    claimType: 'Individual',
    status: 'Pending',
    submittedDate: '2024-06-01',
    lastUpdated: '2024-06-01',
    area: 1.8,
    documents: ['Identity Proof'],
    priority: 'Medium',
    notes: 'Missing Gram Sabha resolution. Needs follow-up.',
  },
  {
    id: 'FRA-2024-004',
    applicantName: 'Kavita Bhil',
    village: 'Jhabua',
    district: 'Jhabua',
    state: 'Madhya Pradesh',
    claimType: 'Individual',
    status: 'Rejected',
    submittedDate: '2023-09-10',
    lastUpdated: '2024-01-15',
    area: 1.2,
    documents: ['Land Map', 'Identity Proof'],
    officerAssigned: 'DFO Verma',
    priority: 'Low',
    notes: 'Rejected — insufficient evidence of 75-year habitation. Appeal filed.',
  },
  {
    id: 'FRA-2024-005',
    applicantName: 'Mangal Kondh',
    village: 'Rayagada',
    district: 'Rayagada',
    state: 'Odisha',
    claimType: 'Habitat',
    status: 'Under Review',
    submittedDate: '2024-02-28',
    lastUpdated: '2024-06-08',
    area: 450.0,
    documents: ['Habitat Map', 'Community Declaration', 'Biodiversity Register', 'Gram Sabha'],
    officerAssigned: 'DFO Das',
    priority: 'Critical',
    notes: 'Particularly Vulnerable Tribal Group (PVTG). Priority case.',
  },
  {
    id: 'FRA-2024-006',
    applicantName: 'Sunita Warli',
    village: 'Dahanu',
    district: 'Palghar',
    state: 'Maharashtra',
    claimType: 'Community',
    status: 'Appeal',
    submittedDate: '2023-07-05',
    lastUpdated: '2024-04-20',
    area: 32.0,
    documents: ['Community Map', 'Gram Sabha', 'Forest Dependency Proof', 'Old Photos'],
    officerAssigned: 'DFO Kulkarni',
    priority: 'High',
  },
]

export const DASHBOARD_STATS: DashboardStats = {
  totalCases: 6,
  pendingCases: 2,
  approvedCases: 2,
  rejectedCases: 1,
  monthlySubmissions: [
    { month: 'Jan', count: 0 },
    { month: 'Feb', count: 1 },
    { month: 'Mar', count: 1 },
    { month: 'Apr', count: 0 },
    { month: 'May', count: 1 },
    { month: 'Jun', count: 3 },
  ],
  districtWise: [
    { district: 'West Singhbhum', count: 2 },
    { district: 'Mandla',         count: 1 },
    { district: 'Rayagada',       count: 1 },
    { district: 'Palghar',        count: 1 },
    { district: 'Lohardaga',      count: 1 },
    { district: 'Jhabua',         count: 0 },
  ],
  claimTypeBreakdown: [
    { type: 'Individual', count: 3 },
    { type: 'Community',  count: 2 },
    { type: 'Habitat',    count: 1 },
  ],
}